spring.application.name=online_booking_system
spring.datasource.url=jdbc:mysql://localhost:3306/bookingdb
spring.datasource.username=root
spring.datasource.password=Shaik@5747
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
tmdb.api.key=fadd39bd5b4d9620e9b9dd16af3e5949
geoapify.api.key=b54ea08d72ce4c7ea0391f881f2569ec
openroute.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjE3ZTdlYWVhZmI0MTQ0OTI5NGVmMThiOWQ2NDIyMzk1IiwiaCI6Im11cm11cjY0In0=
rapid.api.key=5e7ed6cf08msha30216b4f1497dbp1ef477jsn5825e2826cba
rapid.api.host=irctc-indian-railway-pnr-status.p.rapidapi.com